### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by CasparChou** [Joshi425/minecraft-exporter#2]
Hi, I got some error when execute exporter

```
Docker version 19.03.2, build 6a30dfc
docker-compose version 1.24.1, build 4667896b
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
minecraft server version 1.15.2
```

```
$ docker-compose up
Recreating minecraft-exporter_minecraft-exporter_1 ... done
Attaching to minecraft-exporter_minecraft-exporter_1
minecraft-exporter_1  | RCON is enabled for 1.2.3.4
minecraft-exporter_1  | Traceback (most recent call last):
minecraft-exporter_1  |   File "minecraft_exporter.py", line 199, in <module>
minecraft-exporter_1  |     REGISTRY.register(MinecraftCollector())
minecraft-exporter_1  |   File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 24, in register
minecraft-exporter_1  |     names = self._get_names(collector)
minecraft-exporter_1  |   File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 64, in _get_names
minecraft-exporter_1  |     for metric in desc_func():
minecraft-exporter_1  |   File "minecraft_exporter.py", line 190, in collect
minecraft-exporter_1  |     for metric in self.update_metrics_for_player(player)+self.get_server_stats():
minecraft-exporter_1  |   File "minecraft_exporter.py", line 106, in update_metrics_for_player
minecraft-exporter_1  |     data = self.get_player_stats(uuid)
minecraft-exporter_1  |   File "minecraft_exporter.py", line 98, in get_player_stats
minecraft-exporter_1  |     if value["done"] == True:
minecraft-exporter_1  | TypeError: 'int' object is not subscriptable
minecraft-exporter_minecraft-exporter_1 exited with code 1
```

btw,  there is a typo on first line in yours Dockerfile, should be `FROM` not `from`

**Comment by Joshi425** [comment]
I will look into this, can you tell me which modpack you're using? 

thanks for the typo, will fix it.

**Comment by CasparChou** [comment]
```
ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_242 by Private Build
MC 1.15.2 with MCP 20200122.131323
MinecraftForge v31.1.0
```

**Comment by Joshi425** [comment]
I've updated the docker image joshi425/minecraft_exporter
