### ISSUE TITLE
500 errors affecting approx. 50% of requests

### ISSUE THREAD

**Issue by KevBelisle** [Joshi425/minecraft-exporter#20]
After the docker container has been running for a while (can take a few minutes or a few hours), I start getting 500 errors on 50% of requests to /metrics. A container restart fixes the issue, albeit temporarily.

According to container logs, it seems to be an index out of range error:

```
----------------------------------------
Exception happened during processing of request from ('192.168.1.51', 52292)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 152, in do_GET
    output = encoder(registry)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 75, in collect
    for metric in collector.collect():
  File "minecraft_exporter.py", line 310, in collect
    for metric in self.get_server_stats():
  File "minecraft_exporter.py", line 88, in get_server_stats
    overall_tps.add_sample('overall_tps',value=overallregex.findall(resp)[0][1],labels={})
IndexError: list index out of range
----------------------------------------
```

**Comment by Joshi425** [comment]
Hello, thanks for the report.

Looks like tps collection is failing. Which Server Do you run? Do you have Paper or Forge enabled?

**Comment by KevBelisle** [comment]
This is from a Forge server on 1.16.5

**Comment by Joshi425** [comment]
I've tried latest forge `1.16.5-36.2.23` without Problems, which modpack are you running? 
can you paste the output from `forge tps` please?

**Comment by KevBelisle** [comment]
Medieval Minecraft Forge 1.16.5 ~~v48.5~~ v49

**Comment by Joshi425** [comment]
I found the issue and fixed it in the latest version by replacing the minecraft rcon lib
