### ISSUE TITLE
i have error

### ISSUE THREAD

**Issue by iru-dev** [Joshi425/minecraft-exporter#9]
```
git clone https://github.com/Joshi425/minecraft-exporter.git
cd minecraft-exporter/
docker build .
docker run -e RCON_HOST=10.10.88.2 -e RCON_PORT=25575 -e RCON_PASSWORD="qhkrlitoewcs" -e FORGE_SERVER="True" -e DYNMAP_ENABLED="True" -p 9900:8000 -v /opt/minecraft/world:/world joshi425/minecraft_exporter
RCON is enabled for 10.10.88.2
Traceback (most recent call last):
  File "minecraft_exporter.py", line 298, in <module>
    REGISTRY.register(MinecraftCollector())
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "minecraft_exporter.py", line 287, in collect
    for metric in self.update_metrics_for_player(player):
  File "minecraft_exporter.py", line 238, in update_metrics_for_player
    for block, value in data["stats"]["minecraft:crafted"].items():
KeyError: 'minecraft:crafted'
```

**Comment by Joshi425** [comment]
oh that was an oversight on my side, which happens when a Player hasn't craftedanything yet, I've just pushed a fix, please docker pull and restart again
